[colors.primary]
foreground = "#ffdadf"
background = "#29293e"

[colors.normal]
black = "#0d0c1e"
red = "#df4144"
green = "#59df62"
yellow = "#efe55f"
blue = "#6259df"
magenta = "#df59df"
cyan = "#59d6df"
white = "#ffd6db"

[colors.bright]
black = "#55565e"
red = "#ff7883"
green = "#a5ffa5"
yellow = "#fff9a5"
blue = "#aaa5ff"
magenta = "#f9a5ff"
cyan = "#a5ffff"
white = "#3c1d20"

[colors.dim]
black = "#0d0c1e"
red = "#7d363d"
green = "#527c52"
yellow = "#7e7c52"
blue = "#52527c"
magenta = "#78527c"
cyan = "#527c7c"
white = "#55565e"

