#!/bin/bash
export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down
ln -s $SCRIPTPATH/eww/ ~/.config/
export XDG_CONFIG_HOME=~/.config/

EWW_DATA_DIRS="$SCRIPTPATH/eww/assets:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

if command -v eww >/dev/null 2>&1; then
  XDG_DATA_DIRS=$EWW_DATA_DIRS eww daemon &
  eww open peri_bar
elif command -v /usr/bin/eww >/dev/null 2>&1; then
  XDG_DATA_DIRS=$EWW_DATA_DIRS /usr/bin/eww daemon &
  /usr/bin/eww open peri_bar
else
  echo "eww could not be found. Please symlink the eww binary into /usr/bin/" >>$HOME/LEFTWM-THEME-PERI-WARN
fi

if command -v nm-applet >/dev/null 2>&1; then
  pkill -x nm-applet
  nm-applet --indicator &
elif command -v /usr/bin/nm-applet >/dev/null 2>&1; then
  pkill -x nm-applet
  /usr/bin/nm-applet --indicator &
else
  echo "nm-applet could not be found. Please install it (network-manager-gnome on Debian/Ubuntu, network-manager-applet on Arch/Fedora) for the network tray icon" >>$HOME/LEFTWM-THEME-PERI-WARN
fi

leftwm command "LoadTheme $SCRIPTPATH/theme.ron"
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
